esphome:
  name: sw
  friendly_name: sw
  name_add_mac_suffix: true

preferences:
  flash_write_interval: 5min

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

# Enable logging
logger:
  logs:
    sensor: WARN
    dallas.temp.sensor: WARN
    #vl53l0x: WARN
    ld2410s: WARN
      
external_components:
  - source:
      type: local
      path: components


api:

# mqtt:
  # broker: mqtt-master.lan
  # discovery: false
  # topic_prefix: /esp/18AEE8
  # on_message:
    # - topic: "/esp/18AEE8/sensor/wh_capacity/state"
      # then:
        # lambda: |-
          # static bool already_restored = false;
          # if (already_restored)
            # return;
          # auto value = esphome::parse_number<float>(x);
          # if (value.has_value()) {
            # id(last_wh) = value.value();
            # already_restored = true;
          # }  

ota:
  platform: esphome
  password: ""

wifi:
  ssid: "-"
  password: "-"
  fast_connect: true
  use_address: esp-sensor-test.lan

mdns:
  disabled: true

i2c:
debug:
  update_interval: 5s
  
      
      
sensor:

# Debug sensors
  - platform: debug
    loop_time:
      name: "Loop Time"

     
      
output:
  - platform: ledc
    pin: GPIO25
    id: out_pwm

# Example usage in a light
light:
  - platform: empty_light
    name: "Test Light"
    output: out_pwm